### PR TITLE
Web-To-Lead form

### PR DESCRIPTION
**Pull request by rb512**
Added a new feature "web-to-lead form" that allows creation of a customized new lead form, wherein a user can select fields to be displayed for the newly created form.  The form can then be included on an external website, which when submitted, creates a new lead record on railsCRM.

### CODE REVIEW

**Comment by brobertsaz** [comment]
Wow, fantastic!!!  This is great to have done.  I need to help out more and work on some things as well.  I think that the dashboard is maybe the last part to going alpha.  Do you think there needs to be more than that done to start promoting?

Bob Roberts
Ruby on Rails Developer

**Comment by rb512** [comment]
Yea, I think, feature wise, this is good enough.
However, we need to add tests and hook it up to a CI before we start
promoting, what do you think?

On Mon, Oct 22, 2012 at 11:07 AM, Bob Roberts notifications@github.comwrote:

> Wow, fantastic!!! This is great to have done. I need to help out more and
> work on some things as well. I think that the dashboard is maybe the last
> part to going alpha. Do you think there needs to be more than that done to
> start promoting?
> 
> Bob Roberts
> Ruby on Rails Developer
> 
> On Sunday, October 21, 2012 at 11:54 PM, Rahul wrote:
> 
> > Added a new feature "web-to-lead form" that allows creation of a
> > customized new lead form, wherein a user can select fields to be displayed
> > for the newly created form. The form can then be included on an external
> > website, which when submitted, creates a new lead record on railsCRM.
> > You can merge this Pull Request by running:
> > git pull https://github.com/rb512/railscrm master
> > Or view, comment on, or merge it at:
> > https://github.com/brobertsaz/railscrm/pull/1
> > Commit Summary
> > web-to-lead form
> > fixed web form
> > generated web form
> > redirection test
> > mongo db changes
> > corrected url
> > corrected mongoid url
> > web form without validation
> > validation of web form
> > encrypted email
> > 
> > File Changes
> > M Gemfile (4)
> > M Gemfile.lock (4)
> > A app/assets/javascripts/validate.min.js (17)
> > M app/controllers/leads_controller.rb (57)
> > A app/views/leads/convert_form.html.haml (9)
> > M app/views/leads/index.html.haml (2)
> > A app/views/leads/new_web_lead.html.haml (32)
> > A app/views/leads/web_form.html.haml (5)
> > M config/environment.rb (2)
> > M config/mongoid.yml (10)
> > M config/routes.rb (4)
> > A nbproject/private/private.properties (1)
> > A nbproject/private/private.xml (4)
> > A nbproject/private/rake-d.txt (0)
> > A nbproject/project.properties (3)
> > A nbproject/project.xml (9)
> > 
> > Patch Links
> > https://github.com/brobertsaz/railscrm/pull/1.patch
> > https://github.com/brobertsaz/railscrm/pull/1.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/brobertsaz/railscrm/pull/1).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brobertsaz/railscrm/pull/1#issuecomment-9674195.

## 

Rahul

**Comment by brobertsaz** [comment]
All of the parts I added are all test driven so I am not sure what you mean by adding tests?

Bob Roberts
Ruby on Rails Developer

**Comment by rb512** [comment]
I felt, model specs are sparse.

On Mon, Oct 22, 2012 at 11:29 AM, Bob Roberts notifications@github.comwrote:

> All of the parts I added are all test driven so I am not sure what you
> mean by adding tests?
> 
> Bob Roberts
> Ruby on Rails Developer
> 
> On Monday, October 22, 2012 at 11:27 AM, Rahul wrote:
> 
> > Yea, I think, feature wise, this is good enough.
> > However, we need to add tests and hook it up to a CI before we start
> > promoting, what do you think?
> > 
> > On Mon, Oct 22, 2012 at 11:07 AM, Bob Roberts <notifications@github.com(mailto:
> > notifications@github.com)>wrote:
> > 
> > > Wow, fantastic!!! This is great to have done. I need to help out more
> > > and
> > > work on some things as well. I think that the dashboard is maybe the
> > > last
> > > part to going alpha. Do you think there needs to be more than that
> > > done to
> > > start promoting?
> > > 
> > > Bob Roberts
> > > Ruby on Rails Developer
> > > 
> > > On Sunday, October 21, 2012 at 11:54 PM, Rahul wrote:
> > > 
> > > > Added a new feature "web-to-lead form" that allows creation of a
> > > > customized new lead form, wherein a user can select fields to be
> > > > displayed
> > > > for the newly created form. The form can then be included on an
> > > > external
> > > > website, which when submitted, creates a new lead record on railsCRM.
> > > > You can merge this Pull Request by running:
> > > > git pull https://github.com/rb512/railscrm master
> > > > Or view, comment on, or merge it at:
> > > > https://github.com/brobertsaz/railscrm/pull/1
> > > > Commit Summary
> > > > web-to-lead form
> > > > fixed web form
> > > > generated web form
> > > > redirection test
> > > > mongo db changes
> > > > corrected url
> > > > corrected mongoid url
> > > > web form without validation
> > > > validation of web form
> > > > encrypted email
> > > > 
> > > > File Changes
> > > > M Gemfile (4)
> > > > M Gemfile.lock (4)
> > > > A app/assets/javascripts/validate.min.js (17)
> > > > M app/controllers/leads_controller.rb (57)
> > > > A app/views/leads/convert_form.html.haml (9)
> > > > M app/views/leads/index.html.haml (2)
> > > > A app/views/leads/new_web_lead.html.haml (32)
> > > > A app/views/leads/web_form.html.haml (5)
> > > > M config/environment.rb (2)
> > > > M config/mongoid.yml (10)
> > > > M config/routes.rb (4)
> > > > A nbproject/private/private.properties (1)
> > > > A nbproject/private/private.xml (4)
> > > > A nbproject/private/rake-d.txt (0)
> > > > A nbproject/project.properties (3)
> > > > A nbproject/project.xml (9)
> > > > 
> > > > Patch Links
> > > > https://github.com/brobertsaz/railscrm/pull/1.patch
> > > > https://github.com/brobertsaz/railscrm/pull/1.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub (
> > > > https://github.com/brobertsaz/railscrm/pull/1).
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/brobertsaz/railscrm/pull/1#issuecomment-9674195>.
> > 
> > ## 
> > 
> > Rahul
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/brobertsaz/railscrm/pull/1#issuecomment-9674871).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brobertsaz/railscrm/pull/1#issuecomment-9674957.

## 

Rahul

**Comment by brobertsaz** [comment]
I believe more in BDD than TDD.  I rarely use Model tests but always use Integrations tests.

**Comment by rb512** [comment]
Sounds good!

On Mon, Oct 22, 2012 at 12:01 PM, Bob Roberts notifications@github.comwrote:

> I believe more in BDD than TDD. I rarely use Model tests but always use
> Integrations tests.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brobertsaz/railscrm/pull/1#issuecomment-9676141.

## 

Rahul

**Comment by brobertsaz** [comment]
So, probably just the user dashboard is what is left for now.

**Comment by rb512** [comment]
Yep.

On Mon, Oct 22, 2012 at 12:05 PM, Bob Roberts notifications@github.comwrote:

> So, probably just the user dashboard is what is left for now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brobertsaz/railscrm/pull/1#issuecomment-9676291.

## 

Rahul

**Pull request merged**
